application: attendd-testing
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /
  static_files: index.html
  upload: index.html


libraries:
- name: webapp2
  version: "2.5.2"

